# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 446a15a0cc2a65b6620ea1e43f498fa00260721f77b667af36e251b8f12b7a052c597b95967d38c7b0379fe654e8752a8b2fbfe61ec5d8d4002a44d22f4d2319

test:
  secret_key_base: 74f264c62d1ed1c3e7f6ecedfa4cee0af5cb7dc9a7194e0a4de607cc86617fa364b9fe396d1dfc4a75eeb2f9c8533a06810e4d9745c33c55777f1af310c66236

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
